import { supabase } from "./supabase.js";

let addModalInitialized = false;

export function initAddModal(){
 const modal=document.getElementById("addModal");
 if(!modal||addModalInitialized)return;
 addModalInitialized=true;
 const openFromType=type=>open(["video","creator","product","content"].includes(type)?type:"video");
 document.addEventListener("click",e=>{
  const quick=e.target.closest?.("#quickAddButton");
  if(quick){e.preventDefault();e.stopPropagation();document.getElementById("quickAddMenu")?.classList.toggle("hidden");return}
  const addType=e.target.closest?.("[data-add-type]");
  if(addType){e.preventDefault();e.stopPropagation();document.getElementById("quickAddMenu")?.classList.add("hidden");openFromType(addType.dataset.addType);return}
  const libraryAdd=e.target.closest?.("[data-library-add]");
  if(libraryAdd){e.preventDefault();e.stopPropagation();openFromType(libraryAdd.dataset.libraryAdd)}
 });
 document.addEventListener("content-os:open-add",e=>openFromType(typeof e.detail==="string"?e.detail:e.detail?.type||"video"));
 modal.addEventListener("click",e=>{if(e.target===modal||e.target.closest?.("[data-close-add-modal]"))close()});
 async function open(type){
  try{modal.innerHTML=type==="video"?videoTemplate():type==="creator"?creatorTemplate():type==="product"?productTemplate():await contentTemplate();modal.classList.remove("hidden");modal.setAttribute("aria-hidden","false");bind(type)}
  catch(error){console.error("Failed to open add modal:",error);modal.innerHTML=`<div class="add-modal-backdrop"><div class="add-modal-card"><div class="add-modal-header"><div><h2>Could not open form</h2><p>${esc(error?.message||"Unknown error")}</p></div><button type="button" class="add-modal-close" data-close-add-modal>×</button></div></div></div>`;modal.classList.remove("hidden");modal.setAttribute("aria-hidden","false")}
 }
 function close(){modal.classList.add("hidden");modal.setAttribute("aria-hidden","true");modal.innerHTML=""}
 function bind(type){const form=modal.querySelector("form");if(!form)return;if(type==="video")bindVideo(form);if(type==="content")bindContent(form);if(type==="creator"||type==="product")loadNiches(form);form.addEventListener("submit",async e=>{e.preventDefault();const btn=form.querySelector('button[type="submit"]');btn.disabled=true;try{if(type==="video")await saveVideo(form);else if(type==="creator")await saveCreator(form);else if(type==="product")await saveProduct(form);else await saveContent(form);msg(form,"Saved successfully.",false);document.dispatchEvent(new CustomEvent("content-os:data-changed",{detail:{type}}));setTimeout(close,500)}catch(err){msg(form,err.message||"Could not save record.",true)}finally{btn.disabled=false}})}
 async function bindVideo(form){
  await loadCreators(form);await loadNiches(form);await loadPillars(form,"");await loadTags(form);
  const url=form.elements.url,id=form.elements.video_id,platform=form.elements.platform,status=form.querySelector("[data-url-status]");
  function syncFromId(){const value=id.value.trim();if(!value)return;if(platform.value==="Douyin"&&/^\d+$/.test(value)){url.value=`https://www.douyin.com/video/${value}`;status.textContent=`✓ URL tự động tạo từ Video ID ${value}`;status.className="field-status success";url.classList.add("field-valid");url.classList.remove("field-invalid")}else if(platform.value!=="Douyin"){status.textContent="Platform này chưa được cập nhật tự tạo URL. Vui lòng tự điền URL.";status.className="field-status hint";url.classList.remove("field-valid","field-invalid")}}
  function validateUrl(){const value=url.value.trim();if(!value){status.textContent="";status.className="field-status";url.classList.remove("field-invalid","field-valid");return}const parsed=parseDouyinVideoUrl(value);if(!parsed){status.textContent="Vui lòng nhập đúng link video Douyin.";status.className="field-status error";url.classList.add("field-invalid");url.classList.remove("field-valid");return}id.value=parsed;status.textContent=`✓ Video ID: ${parsed}`;status.className="field-status success";url.classList.remove("field-invalid");url.classList.add("field-valid")}
  url.addEventListener("input",validateUrl);id.addEventListener("input",syncFromId);platform.addEventListener("change",syncFromId);
  form.elements.creator_id.addEventListener("change",async()=>{const creatorId=form.elements.creator_id.value;if(!creatorId)return;const {data,error}=await supabase.from("creators").select("niche_id,download_path").eq("id",creatorId).maybeSingle();if(error){msg(form,error.message,true);return}if(data){form.elements.niche_id.value=data.niche_id||"";await loadPillars(form,data.niche_id||"");form.elements.download_path.value=data.download_path||""}});
  form.elements.niche_id.addEventListener("change",()=>loadPillars(form,form.elements.niche_id.value));form.elements.pillar_id.addEventListener("change",()=>loadTopics(form));
 }
 async function bindContent(form){const videoSelect=form.elements.video_id;const {data,error}=await supabase.from("videos").select("id,video_id,title,status,niche_id,pillar_id,topic_id,creator_id,creators(creator_name,handle)").in("status",["editing","edited","ready","scheduled","published"]).order("created_at",{ascending:false});if(error){videoSelect.innerHTML='<option value="">Videos unavailable</option>';return}videoSelect.innerHTML='<option value="">Select video</option>';(data||[]).forEach(v=>videoSelect.insertAdjacentHTML("beforeend",`<option value="${esc(v.id)}">${esc(v.video_id||"Untitled")}</option>`));videoSelect.addEventListener("change",async()=>{const v=(data||[]).find(x=>x.id===videoSelect.value);if(!v)return;await loadPillars(form,v.niche_id||"");form.elements.pillar_id.value=v.pillar_id||"";if(v.pillar_id){await loadTopics(form);form.elements.topic_id.value=v.topic_id||""}else form.elements.topic_id.value=""});await loadTags(form)}
 async function loadCreators(form){const s=form.elements.creator_id,{data,error}=await supabase.from("creators").select("id,creator_name,handle,creator_code").eq("status","active").order("creator_name");if(error){s.innerHTML='<option value="">Creators unavailable</option>';return}s.innerHTML='<option value="">Select creator</option>';(data||[]).forEach(r=>s.insertAdjacentHTML("beforeend",`<option value="${esc(r.id)}">${esc(r.creator_name||r.handle||r.creator_code)}${r.handle?` · @${esc(r.handle.replace(/^@/,""))}`:""}</option>`))}
 async function loadNiches(form){const s=form.elements.niche_id;if(!s)return;const {data}=await supabase.from("niches").select("id,name,niche_code").eq("status","active").order("sort_order");s.innerHTML='<option value="">Select niche</option>';(data||[]).forEach(r=>s.insertAdjacentHTML("beforeend",`<option value="${r.id}">${esc(r.name)} (${esc(r.niche_code)})</option>`))}
 async function loadPillars(form,niche){const s=form.elements.pillar_id;if(!s)return;let q=supabase.from("pillars").select("id,name,pillar_code").order("sort_order");if(niche)q=q.eq("niche_id",niche);const {data}=await q;s.innerHTML='<option value="">Select pillar</option>';(data||[]).forEach(r=>s.insertAdjacentHTML("beforeend",`<option value="${r.id}">${esc(r.name)} (${esc(r.pillar_code)})</option>`));if(form.elements.topic_id)form.elements.topic_id.innerHTML='<option value="">Select topic</option>'}
 async function loadTopics(form){const s=form.elements.topic_id,p=form.elements.pillar_id.value;s.innerHTML='<option value="">Select topic</option>';if(!p)return;const {data}=await supabase.from("topics").select("id,name,topic_code").eq("pillar_id",p).order("sort_order");(data||[]).forEach(r=>s.insertAdjacentHTML("beforeend",`<option value="${r.id}">${esc(r.name)} (${esc(r.topic_code)})</option>`))}
 async function loadTags(form){const box=form.querySelector("#videoTags");if(!box)return;const {data}=await supabase.from("tags").select("id,name").order("name").limit(300);if(!data?.length){box.innerHTML='<span class="taxonomy-muted">No tags yet. Add them in Taxonomy.</span>';return}box.innerHTML=data.map(t=>`<label class="tag-option"><input type="checkbox" name="tag_ids" value="${t.id}"><span>#${esc(t.name)}</span></label>`).join("")}
 async function saveVideo(form){const video_id=form.elements.video_id.value.trim();if(!video_id)throw new Error("Video ID is required.");const url=form.elements.url.value.trim();if(form.elements.platform.value==="Douyin"&&!parseDouyinVideoUrl(url))throw new Error("Vui lòng nhập đúng link video Douyin.");const {data:dup}=await supabase.from("videos").select("id").eq("video_id",video_id).limit(1);if(dup?.length)throw new Error(`Video ID “${video_id}” already exists.`);const payload={video_code:`VID-${Date.now()}`,video_id,platform_url:url,platform:form.elements.platform.value,creator_id:form.elements.creator_id.value||null,niche_id:form.elements.niche_id.value||null,pillar_id:form.elements.pillar_id.value||null,topic_id:form.elements.topic_id.value||null,title:form.elements.title.value.trim()||null,hook:form.elements.hook.value.trim()||null,caption:form.elements.caption.value.trim()||null,status:form.elements.status.value};if(!payload.creator_id)throw new Error("Video Creator is required.");const {data,error}=await supabase.from("videos").insert(payload).select("id").single();if(error)throw error;const ids=[...form.querySelectorAll('input[name="tag_ids"]:checked')].map(x=>x.value);if(ids.length){const {error:tagError}=await supabase.from("video_tags").insert(ids.map(tag_id=>({video_id:data.id,tag_id})));if(tagError)throw tagError}}
 async function saveContent(form){const id=form.elements.video_id.value;if(!id)throw new Error("Please select a video.");const payload={title:form.elements.title.value.trim()||null,hook:form.elements.hook.value.trim()||null,caption:form.elements.caption.value.trim()||null,pillar_id:form.elements.pillar_id.value||null,topic_id:form.elements.topic_id.value||null};const {error}=await supabase.from("videos").update(payload).eq("id",id);if(error)throw error;await supabase.from("video_tags").delete().eq("video_id",id);const ids=[...form.querySelectorAll('input[name="tag_ids"]:checked')].map(x=>x.value);if(ids.length)await supabase.from("video_tags").insert(ids.map(tag_id=>({video_id:id,tag_id})))}
 async function saveCreator(form){const code=form.elements.creator_code?.value||null;const payload={creator_code:code,creator_name:form.elements.creator_name.value.trim(),handle:form.elements.handle.value.trim()||null,platform:form.elements.platform.value,niche_id:form.elements.niche_id.value,profile_url:form.elements.profile_url.value.trim()||null,creator_type:form.elements.creator_type.value.trim()||null,content_style:form.elements.content_style.value.trim()||null,download_path:form.elements.download_path.value.trim()||null,status:form.elements.status.value};if(!payload.creator_name||!payload.platform||!payload.niche_id)throw new Error("Creator Name, Platform and Niche are required.");const {error}=await supabase.from("creators").insert(payload);if(error)throw error}
 async function saveProduct(form){const payload={product_code:`PROD-${Date.now()}`,niche_id:form.elements.niche_id.value||null,category:form.elements.category.value.trim()||null,product_name:form.elements.product_name.value.trim(),brand:form.elements.brand.value.trim()||null,platform:form.elements.platform.value.trim()||null,product_url:form.elements.product_url.value.trim()||null,price:form.elements.price.value?Number(form.elements.price.value):null,affiliate_url:form.elements.affiliate_url.value.trim()||null,commission_rate:form.elements.commission_rate.value?Number(form.elements.commission_rate.value):null,repeat_purchase:form.elements.repeat_purchase.value==="true",affiliate_potential:form.elements.affiliate_potential.value?Number(form.elements.affiliate_potential.value):null,notes:form.elements.notes.value.trim()||null,status:form.elements.status.value};if(!payload.product_name)throw new Error("Product name is required.");const {error}=await supabase.from("products").insert(payload);if(error)throw error}
 function parseDouyinVideoUrl(value){try{const u=new URL(value);if(!["www.douyin.com","douyin.com","m.douyin.com"].includes(u.hostname))return"";const modalId=u.searchParams.get("modal_id");if(modalId&&/^\d+$/.test(modalId))return modalId;const match=u.pathname.match(/\/video\/(\d+)/);return match?.[1]||""}catch{return""}}
 function parseAnyVideoId(value){try{const u=new URL(value);const match=u.pathname.match(/\/video\/(\d+)/);return match?.[1]||u.searchParams.get("video_id")||""}catch{return""}}
 function msg(f,text,error){const b=f.querySelector(".add-form-message");b.textContent=text;b.classList.toggle("error",error);b.classList.remove("hidden")}
 const field=(l,n,t="text",a="")=>`<label class="add-field"><span>${l}</span><input name="${n}" type="${t}" ${a}></label>`;
 const select=(l,n,opts,a="")=>`<label class="add-field"><span>${l}</span><select name="${n}" ${a}>${opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join("")}</select>`;
 const footer=()=>`<div class="add-form-message hidden"></div><div class="add-modal-actions"><button type="button" class="table-action" data-close-add-modal>Cancel</button><button type="submit" class="capture-button">Save</button></div>`;
 const shell=(title,desc,body)=>`<div class="add-modal-backdrop"><div class="add-modal-card" role="dialog" aria-modal="true"><div class="add-modal-header"><div><h2>${title}</h2><p>${desc}</p></div><button type="button" class="add-modal-close" data-close-add-modal>×</button></div><form class="add-modal-form">${body}${footer()}</form></div></div>`;
 function videoTemplate(){return shell("Add Video","Record a video in Library. Status starts at Recorded.",`<div class="add-form-grid">${field("Video URL","url","url",'required placeholder="https://www.douyin.com/..."')}<div class="add-field-wrap">${field("Video ID","video_id","text",'required placeholder="Auto-filled from URL"')}<small data-url-status class="field-status"></small></div>${select("Creator","creator_id",[["","Loading creators..."]],'required')}${select("Platform","platform",[["Douyin","Douyin"],["Xiaohongshu","Xiaohongshu"],["YouTube","YouTube"],["Instagram","Instagram"],["TikTok","TikTok"]],'required')}${select("Niche","niche_id",[["","Select niche"]])}${select("Pillar","pillar_id",[["","Select pillar"]])}${select("Topic","topic_id",[["","Select topic"]])}${select("Status","status",VIDEO_STATUSES.map(s=>[s,STATUS_LABELS[s]]))}${field("Title","title","text",'placeholder="Optional"')}${field("Hook","hook","text",'placeholder="Optional"')}${field("Caption","caption","text",'placeholder="Optional"')}${field("Download Path","download_path","text",'readonly placeholder="From creator"')}</div><div class="taxonomy-picker"><div class="taxonomy-picker-title">Tags</div><div id="videoTags" class="tag-options"></div></div>`) }
 function creatorTemplate(){return shell("Add Creator","Creator Code is generated automatically.",`<input type="hidden" name="creator_code"><div class="add-form-grid">${field("Creator Name","creator_name","text",'required placeholder="Creator display name"')}${field("Handle / Username","handle","text",'placeholder="@username"')}${select("Platform","platform",[["Douyin","Douyin"],["Xiaohongshu","Xiaohongshu"],["YouTube","YouTube"],["Instagram","Instagram"],["TikTok","TikTok"]],'required')}${select("Niche","niche_id",[["","Select niche"]],'required')}${field("Profile URL","profile_url","url",'placeholder="https://..."')}${field("Creator Type","creator_type","text",'placeholder="Optional"')}${field("Content Style","content_style","text",'placeholder="Optional"')}${field("Download Path","download_path","text",'placeholder="Shared folder for this creator"')}${select("Status","status",[["active","Active"],["watching","Watching"],["inactive","Inactive"]])}</div>`) }
 function productTemplate(){return shell("Add Product","Save a product/affiliate record.",`<div class="add-form-grid">${field("Product Name","product_name","text",'required placeholder="Product name"')}${field("Category","category","text",'placeholder="Category"')}${field("Brand","brand","text",'placeholder="Brand"')}${field("Platform","platform","text",'placeholder="Platform"')}${select("Niche","niche_id",[["","Select niche"]])}${field("Product URL","product_url","url",'placeholder="https://..."')}${field("Price","price","number",'step="0.01" min="0" placeholder="0"')}${field("Affiliate URL","affiliate_url","url",'placeholder="https://..."')}${field("Commission Rate","commission_rate","number",'step="0.01" min="0" placeholder="0"')}${select("Repeat Purchase","repeat_purchase",[["false","No"],["true","Yes"]])}${field("Affiliate Potential","affiliate_potential","number",'step="0.01" min="0" placeholder="0"')}${select("Status","status",[["researching","Researching"],["selected","Selected"],["active","Active"],["archived","Archived"]])}<label class="add-field add-field-full"><span>Notes</span><textarea name="notes" rows="3" placeholder="Optional notes"></textarea></label></div>`)}
 async function contentTemplate(){return shell("Edit Content","Update title, hook, caption, taxonomy, and tags.",`<div class="add-form-grid">${select("Video","video_id",[["","Loading videos..."]])}${field("Title","title","text",'placeholder="Content title"')}${field("Hook","hook","text",'placeholder="Hook"')}${field("Caption","caption","text",'placeholder="Caption"')}${select("Pillar","pillar_id",[["","Select pillar"]])}${select("Topic","topic_id",[["","Select topic"]])}</div><div class="taxonomy-picker"><div class="taxonomy-picker-title">Tags</div><div id="videoTags" class="tag-options"></div></div>`) }
}
