import { supabase } from "./supabase.js";

document.addEventListener("DOMContentLoaded",()=>{
  const button=document.getElementById("quickAddButton"),menu=document.getElementById("quickAddMenu"),modal=document.getElementById("addModal");
  if(!button||!menu||!modal)return;
  button.addEventListener("click",e=>{e.stopPropagation();menu.classList.toggle("hidden")});
  menu.addEventListener("click",e=>{const option=e.target.closest("[data-add-type]");if(!option)return;menu.classList.add("hidden");openModal(option.dataset.addType)});
  modal.addEventListener("click",e=>{if(e.target===modal||e.target.closest("[data-close-add-modal]"))closeModal()});
  document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.classList.contains("hidden"))closeModal()});

  function openModal(type){modal.innerHTML=type==="video"?videoTemplate():type==="creator"?creatorTemplate():productTemplate();modal.classList.remove("hidden");modal.setAttribute("aria-hidden","false");bind(type)}
  function closeModal(){modal.classList.add("hidden");modal.setAttribute("aria-hidden","true");modal.innerHTML=""}
  function bind(type){const form=modal.querySelector("form");if(!form)return;if(type==="video")bindVideo(form);if(type==="creator"||type==="product")loadNiches(form);form.addEventListener("submit",async e=>{e.preventDefault();const submit=form.querySelector("button[type=submit]");submit.disabled=true;try{if(type==="video")await saveVideo(form);else if(type==="creator")await saveCreator(form);else await saveProduct(form);message(form,"Saved successfully.",false);setTimeout(closeModal,650)}catch(error){console.error(error);message(form,error.message||"Could not save record.",true)}finally{submit.disabled=false}})}

  async function bindVideo(form){
    await loadCreators(form);
    await loadNiches(form);
    form.elements.url.addEventListener("input",()=>{form.elements.video_id.value=extractVideoId(form.elements.url.value);validateVideoId(form)});
    form.elements.video_id.addEventListener("input",()=>{const id=form.elements.video_id.value.trim();if(/^\d+$/.test(id))form.elements.url.value=`https://www.douyin.com/video/${id}`;validateVideoId(form)});
    form.elements.creator_id.addEventListener("change",async()=>{const creatorId=form.elements.creator_id.value;if(!creatorId)return;const {data}=await supabase.from("creators").select("niche_id,download_path").eq("id",creatorId).maybeSingle();if(data){form.elements.niche_id.value=data.niche_id||"";await loadPillars(form,data.niche_id||"");form.elements.download_path.value=data.download_path||""}});
    form.elements.niche_id.addEventListener("change",()=>loadPillars(form,form.elements.niche_id.value));
    form.elements.pillar_id.addEventListener("change",()=>loadTopics(form));
    await loadPillars(form,"");
    await loadTags(form);
  }

  async function loadCreators(form){const select=form.elements.creator_id;if(!select)return;const {data,error}=await supabase.from("creators").select("id,creator_name,handle,creator_code").eq("status","active").order("creator_name");if(error){select.innerHTML='<option value="">Creators unavailable</option>';return}select.innerHTML='<option value="">Select creator</option>';(data||[]).forEach(r=>select.insertAdjacentHTML("beforeend",`<option value="${esc(r.id)}">${esc(r.creator_name||r.handle||r.creator_code)}${r.handle?` · @${esc(r.handle.replace(/^@/,""))}`:""}</option>`))}
  async function loadNiches(form){const select=form.elements.niche_id;if(!select)return;const {data,error}=await supabase.from("niches").select("id,name,niche_code").eq("status","active").order("sort_order");if(error)return;select.innerHTML='<option value="">Select niche</option>';(data||[]).forEach(r=>select.insertAdjacentHTML("beforeend",`<option value="${esc(r.id)}">${esc(r.name)} (${esc(r.niche_code)})</option>`))}
  async function loadPillars(form,nicheId){const select=form.elements.pillar_id;if(!select)return;let q=supabase.from("pillars").select("id,name,pillar_code,niche_id").order("sort_order");if(nicheId)q=q.eq("niche_id",nicheId);const {data,error}=await q;select.innerHTML=error?'<option value="">Pillars unavailable</option>':'<option value="">Select pillar</option>';(data||[]).forEach(r=>select.insertAdjacentHTML("beforeend",`<option value="${esc(r.id)}">${esc(r.name)} (${esc(r.pillar_code)})</option>`));select.value=""}
  async function loadTopics(form){const select=form.elements.topic_id,pillarId=form.elements.pillar_id.value;select.innerHTML='<option value="">Select topic</option>';if(!pillarId)return;const {data}=await supabase.from("topics").select("id,name,topic_code").eq("pillar_id",pillarId).order("sort_order");(data||[]).forEach(r=>select.insertAdjacentHTML("beforeend",`<option value="${esc(r.id)}">${esc(r.name)} (${esc(r.topic_code)})</option>`))}
  async function loadTags(form){const box=form.querySelector("#videoTags");if(!box)return;const {data,error}=await supabase.from("tags").select("id,name").order("name").limit(300);if(error){box.innerHTML='<span class="taxonomy-muted">Tags unavailable.</span>';return}box.innerHTML=(data||[]).map(t=>`<label class="tag-option"><input type="checkbox" name="tag_ids" value="${esc(t.id)}"><span>${esc(t.name)}</span></label>`).join("")||'<span class="taxonomy-muted">No tags yet. Add them in Taxonomy.</span>'}

  async function validateVideoId(form){const id=form.elements.video_id.value.trim(),box=form.querySelector('[data-status="video"]');if(!id){box.textContent="";return false}const {data,error}=await supabase.from("videos").select("id").eq("video_id",id).limit(1);if(error){box.textContent="";return false}const duplicate=Boolean(data?.length);box.textContent=duplicate?`⚠ Video ID ${id} already exists.`:"✓ Video ID available.";box.classList.toggle("error",duplicate);box.classList.toggle("success",!duplicate);return duplicate}

  async function saveVideo(form){if(await validateVideoId(form))throw new Error(`Video ID “${form.elements.video_id.value.trim()}” already exists.`);const payload={video_code:`VID-${Date.now()}`,video_id:form.elements.video_id.value.trim(),platform_url:form.elements.url.value.trim(),platform:form.elements.platform.value.trim(),creator_id:form.elements.creator_id.value||null,niche_id:form.elements.niche_id.value||null,pillar_id:form.elements.pillar_id.value||null,topic_id:form.elements.topic_id.value||null,title:form.elements.title.value.trim()||null,hook:form.elements.hook.value.trim()||null,caption:form.elements.caption.value.trim()||null,status:form.elements.status.value};if(!payload.video_id||!payload.platform_url||!payload.creator_id)throw new Error("Video URL, Video ID and Creator are required.");const {data,error}=await supabase.from("videos").insert(payload).select("id").single();if(error)throw error;if(data?.id){const tagIds=[...form.querySelectorAll('input[name="tag_ids"]:checked')].map(i=>i.value);if(tagIds.length)await supabase.from("video_tags").insert(tagIds.map(tag_id=>({video_id:data.id,tag_id})))}}

  async function saveCreator(form){const payload={creator_name:form.elements.creator_name.value.trim(),handle:form.elements.handle.value.trim()||null,platform:form.elements.platform.value.trim(),niche_id:form.elements.niche_id.value||null,profile_url:form.elements.profile_url.value.trim()||null,creator_type:form.elements.creator_type.value.trim()||null,content_style:form.elements.content_style.value.trim()||null,download_path:form.elements.download_path.value.trim()||null,status:form.elements.status.value};if(!payload.creator_name||!payload.platform||!payload.niche_id)throw new Error("Creator Name, Platform and Niche are required.");const {error}=await supabase.from("creators").insert(payload);if(error)throw error}
  async function saveProduct(form){const payload={product_code:`PROD-${Date.now()}`,product_name:form.elements.product_name.value.trim(),product_url:form.elements.product_url.value.trim()||null,platform:form.elements.platform.value.trim()||null,price:form.elements.price.value?Number(form.elements.price.value):null,status:form.elements.status.value,niche_id:form.elements.niche_id.value||null,notes:form.elements.notes.value.trim()||null};if(!payload.product_name)throw new Error("Product name is required.");const {error}=await supabase.from("products").insert(payload);if(error)throw error}

  function extractVideoId(value){try{const u=new URL(value.trim());const modalId=u.searchParams.get("modal_id");if(modalId&&/^\d+$/.test(modalId))return modalId;const match=u.pathname.match(/\/video\/(\d+)/);if(match)return match[1];return u.searchParams.get("vid")||u.searchParams.get("video_id")||""}catch{return""}}
  function message(form,text,error){const box=form.querySelector(".add-form-message");box.textContent=text;box.classList.toggle("error",error);box.classList.remove("hidden")}
  function esc(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c]))}
  const field=(label,name,type="text",attrs="")=>`<label class="add-field"><span>${label}</span><input name="${name}" type="${type}" ${attrs}></label>`;
  const select=(label,name,options,attrs="")=>`<label class="add-field"><span>${label}</span><select name="${name}" ${attrs}>${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join("")}</select></label>`;
  const footer=()=>`<div class="add-form-message hidden"></div><div class="add-modal-actions"><button type="button" class="table-action" data-close-add-modal>Cancel</button><button type="submit" class="capture-button">Save</button></div>`;
  const shell=(title,desc,body)=>`<div class="add-modal-backdrop"><div class="add-modal-card" role="dialog" aria-modal="true"><div class="add-modal-header"><div><h2>${title}</h2><p>${desc}</p></div><button type="button" class="add-modal-close" data-close-add-modal>×</button></div><form class="add-modal-form">${body}${footer()}</form></div></div>`;
  function videoTemplate(){return shell("Add Video","Record a video in Library. Status starts at Recorded until you begin processing.",`<div class="add-form-grid">${field("Video URL","url","url",'required placeholder="https://www.douyin.com/..."')}${field("Video ID","video_id","text",'required placeholder="Auto-filled from URL"')}${select("Creator","creator_id",[["","Loading creators..."]],'required')}${select("Platform","platform",[["Douyin","Douyin"],["Xiaohongshu","Xiaohongshu"],["YouTube","YouTube"],["Instagram","Instagram"],["TikTok","TikTok"]],'required')}${select("Niche","niche_id",[["","Select niche"]])}${select("Pillar","pillar_id",[["","Select pillar"]])}${select("Topic","topic_id",[["","Select topic"]])}${select("Status","status",VIDEO_STATUSES.map(s=>[s,STATUS_LABELS[s]]))}${field("Title","title","text",'placeholder="Optional"')}${field("Hook","hook","text",'placeholder="Optional"')}${field("Caption","caption","text",'placeholder="Optional"')}${field("Download Path","download_path","text",'readonly placeholder="From creator"')}</div><div class="taxonomy-picker"><div class="taxonomy-picker-title">Tags</div><div id="videoTags" class="tag-options"></div></div><div class="creator-lookup-status" data-status="video"></div>`)}
  function creatorTemplate(){return shell("Add Creator","Create a creator record. Creator Code is generated automatically as NICHE-CODE-CREATOR-SEQUENCE.",`<div class="add-form-grid">${field("Creator Name","creator_name","text",'required placeholder="Creator display name"')}${field("Handle / Username","handle","text",'placeholder="@username"')}${select("Platform","platform",[["Douyin","Douyin"],["Xiaohongshu","Xiaohongshu"],["YouTube","YouTube"],["Instagram","Instagram"],["TikTok","TikTok"]],'required')}${select("Niche","niche_id",[["","Select niche"]],'required')}${field("Profile URL","profile_url","url",'placeholder="https://..."')}${field("Creator Type","creator_type","text",'placeholder="Optional"')}${field("Content Style","content_style","text",'placeholder="Optional"')}${field("Download Path","download_path","text",'placeholder="Shared folder for this creator"')}${select("Status","status",[["active","Active"],["watching","Watching"],["inactive","Inactive"]])}</div>`)}
  function productTemplate(){return shell("Add Product","Save an affiliate/product record.",`<div class="add-form-grid">${field("Product Name","product_name","text",'required placeholder="Product name"')}${field("Platform","platform","text",'placeholder="Platform"')}${field("Product URL","product_url","url",'placeholder="https://..."')}${field("Price","price","number",'step="0.01" min="0" placeholder="0"')}${select("Status","status",[["active","Active"],["testing","Testing"],["inactive","Inactive"]])}${select("Niche","niche_id",[["","Select niche"]])}${field("Notes","notes","text",'placeholder="Optional"')}</div>`)}
});
