import { supabase } from "./supabase.js";

document.addEventListener("DOMContentLoaded",async()=>{initRouter();await initNicheSelector();initMobileMenu();initQuickAdd();});

async function initNicheSelector(){const button=document.getElementById("nicheButton"),menu=document.getElementById("nicheMenu");if(!button||!menu)return;await loadNiches();button.addEventListener("click",event=>{event.stopPropagation();menu.classList.toggle("hidden")});menu.addEventListener("click",event=>{const option=event.target.closest(".niche-option");if(!option)return;selectNiche(option.dataset.niche);menu.classList.add("hidden")});document.addEventListener("click",()=>menu.classList.add("hidden"))}

async function loadNiches(){try{const{data,error}=await supabase.from("niches").select("id,niche_code,name,description,status,sort_order").eq("status","active").order("sort_order",{ascending:true});if(error)throw error;renderNicheMenu([{id:null,niche_code:"ALL",name:"All Niches",description:"Master database"},...(data||[])]);selectNiche(getCurrentNiche())}catch(error){console.error("Failed to load niches:",error)}}

function renderNicheMenu(niches){const menu=document.getElementById("nicheMenu");menu.innerHTML='<div class="niche-menu-header"><strong>Select Niche</strong></div>';niches.forEach(niche=>{const option=document.createElement("button");option.className="niche-option";option.dataset.niche=niche.niche_code;option.dataset.nicheId=niche.id||"";let dotClass="master";if(niche.niche_code==="FAS")dotClass="fashion";else if(niche.niche_code==="GRM")dotClass="grooming";else if(niche.niche_code==="DIG")dotClass="digital";option.innerHTML=`<span class="niche-dot ${dotClass}"></span><div><strong>${niche.name}</strong><small>${niche.niche_code==="ALL"?"Master database":niche.niche_code}</small></div>`;menu.appendChild(option)})}

function selectNiche(nicheCode){const option=document.querySelector(`.niche-option[data-niche="${nicheCode}"]`);if(!option)return;const nicheId=option.dataset.nicheId||null;setCurrentNiche(nicheCode,nicheId);const name=document.getElementById("currentNicheName"),code=document.getElementById("currentNicheCode");if(name)name.textContent=option.querySelector("strong").textContent;if(code)code.textContent=option.querySelector("small").textContent;document.querySelectorAll(".niche-option").forEach(item=>item.classList.toggle("active",item.dataset.niche===nicheCode));const dot=document.getElementById("currentNicheDot");if(dot){dot.classList.remove("master","fashion","grooming","digital");dot.classList.add(nicheCode==="FAS"?"fashion":nicheCode==="GRM"?"grooming":nicheCode==="DIG"?"digital":"master")}window.dispatchEvent(new CustomEvent("nicheChanged",{detail:{nicheCode,nicheId}}))}

function initQuickAdd(){const button=document.getElementById("quickAddButton"),menu=document.getElementById("quickAddMenu");if(!button||!menu)return;button.addEventListener("click",event=>{event.stopPropagation();menu.classList.toggle("hidden")});menu.addEventListener("click",event=>{const item=event.target.closest("button[data-add-type]");if(!item)return;menu.classList.add("hidden");if(item.dataset.addType==="source"){window.location.hash="#research";setTimeout(()=>document.getElementById("sourceUrlInput")?.focus(),250)}});document.addEventListener("click",()=>menu.classList.add("hidden"))}

function initMobileMenu(){const button=document.getElementById("mobileMenuButton"),sidebar=document.getElementById("sidebar");if(!button||!sidebar)return;button.addEventListener("click",()=>sidebar.classList.toggle("open"))}
