import { supabase } from "./supabase.js";

const CONFIG={creator:{label:"Creators",table:"creators",columns:["creator_name","handle","platform","niche_code","profile_url","creator_type","content_style","download_path","status"]},video:{label:"Videos",table:"videos",columns:["video_id","platform_url","platform","creator_handle","niche_code","pillar_code","topic_code","title","hook","caption","status"]},product:{label:"Products",table:"products",columns:["product_name","category","brand","platform","niche_code","product_url","price","affiliate_url","commission_rate","repeat_purchase","affiliate_potential","notes","status"]},niches:{label:"Niches",table:"niches",columns:["name","niche_code","description","status"]},pillars:{label:"Pillars",table:"pillars",columns:["name","pillar_code","niche_code","description","status"]},topics:{label:"Topics",table:"topics",columns:["name","topic_code","niche_code","pillar_code","description","status"]},keywords:{label:"Keywords",table:"keywords",columns:["keyword","keyword_code","niche_code","pillar_code","topic_code","category","vietnamese_meaning","platform","status"]},tags:{label:"Tags",table:"tags",columns:["name","niche_code","pillar_code","topic_code","description"]},all:{label:"All Taxonomy",table:null,columns:["type","name","code","niche_code","pillar_code","topic_code","description","category","vietnamese_meaning","platform","status"]}};

function init(){if(window.__bulkImportReady)return;window.__bulkImportReady=true;document.addEventListener("content-os:open-bulk",e=>open(e.detail?.type||e.detail||"video"));const observer=new MutationObserver(()=>injectButtons());observer.observe(document.body,{childList:true,subtree:true});injectButtons()}

function injectButtons(){
 const lv=document.getElementById("libraryView"),toolbar=lv?.querySelector(".library-toolbar");
 if(toolbar&&!toolbar.querySelector("[data-auto-bulk]")){const active=lv.closest("#libraryWorkspace")?.querySelector("[data-library-view].active")?.dataset.libraryView;const type=active==="creators"?"creator":active==="videos"?"video":active==="products"?"product":null;if(type){const b=document.createElement("button");b.type="button";b.className="table-action bulk-add-button";b.dataset.autoBulk="true";b.textContent="＋ Bulk CSV";b.onclick=()=>document.dispatchEvent(new CustomEvent("content-os:open-bulk",{detail:{type}}));toolbar.appendChild(b)}}
 const tax=document.getElementById("taxonomyWorkspace"),form=tax?.querySelector("#taxonomyForm");
 if(form){
   const active=tax.querySelector("[data-taxonomy-type].active")?.dataset.taxonomyType||"niches";
   const actions=form.querySelector(".research-form-actions");
   let b=actions?.querySelector("[data-tax-bulk-action]");
   if(actions&&!b){b=document.createElement("button");b.type="button";b.className="table-action bulk-add-button taxonomy-bulk-button";b.dataset.taxBulkAction="true";actions.appendChild(b)}
   if(b){b.textContent=`＋ Bulk ${CONFIG[active]?.label||"CSV"}`;b.onclick=()=>document.dispatchEvent(new CustomEvent("content-os:open-bulk",{detail:{type:active}}))}
   const all=tax.querySelector("[data-taxonomy-bulk-all]");
   if(all&&!all.dataset.bound){all.dataset.bound="true";all.onclick=()=>document.dispatchEvent(new CustomEvent("content-os:open-bulk",{detail:{type:"all"}}))}
 }
}

function open(type){const cfg=CONFIG[type];if(!cfg)return;document.getElementById("bulkImportModal")?.remove();const modal=document.createElement("div");modal.id="bulkImportModal";modal.className="library-edit-overlay";modal.innerHTML=`<div class="library-edit-modal bulk-import-modal"><div class="modal-header"><div><h3>Bulk Add ${cfg.label}</h3><p>Download the template, fill it in, then upload the CSV.</p></div><button class="modal-close" data-close>×</button></div><div class="bulk-import-body"><div class="bulk-import-actions"><button type="button" class="button secondary" data-template>Download CSV template</button><label class="button secondary bulk-file-label">Choose CSV<input type="file" accept=".csv,text/csv" data-file hidden></label></div><div class="bulk-file-name" data-file-name>No file selected</div><div class="bulk-preview" data-preview><span>CSV columns:</span> ${cfg.columns.map(c=>`<code>${c}</code>`).join(" ")}</div><div class="add-form-message hidden" data-message></div></div><div class="modal-actions"><button type="button" class="button secondary" data-close>Cancel</button><button type="button" class="button primary" data-import disabled>Import</button></div></div>`;document.body.appendChild(modal);modal.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>modal.remove());modal.querySelector("[data-template]").onclick=()=>downloadTemplate(type);modal.querySelector("[data-file]").onchange=e=>previewFile(modal,type,e.target.files[0]);modal.querySelector("[data-import]").onclick=()=>importFile(modal,type)}

function downloadTemplate(type){const cfg=CONFIG[type],csv=cfg.columns.join(",")+"\n"+cfg.columns.map(()=>"").join(",")+"\n";download(csv,`${type}-template.csv`)}

async function previewFile(modal,type,file){if(!file)return;modal.querySelector("[data-file-name]").textContent=file.name;try{const text=await file.text(),rows=parseCsv(text);if(type==="all")rows=rows.filter(r=>r.type?.trim());modal._rows=rows;modal.querySelector("[data-preview]").innerHTML=`<strong>${rows.length}</strong> rows detected. <span>Columns: ${Object.keys(rows[0]||{}).map(x=>`<code>${esc(x)}</code>`).join(" ")}</span>`;modal.querySelector("[data-import]").disabled=!rows.length}catch(e){message(modal,e.message,true)}}

async function importFile(modal,type){const cfg=CONFIG[type],rows=modal._rows||[];if(!rows.length)return;const btn=modal.querySelector("[data-import]");btn.disabled=true;try{if(type==="all"){const result=await normalizeAll(rows);let total=0;for(const [table,payload] of Object.entries(result)){if(!payload.length)continue;const {error}=await supabase.from(table).insert(payload);if(error)throw new Error(`${table}: ${error.message}`);total+=payload.length}if(!total)throw new Error("No valid taxonomy rows found.");message(modal,`${total} taxonomy records imported successfully.`,false)}else{const payload=await normalize(type,rows);if(!payload.length)throw new Error("No valid rows found.");const {error}=await supabase.from(cfg.table).insert(payload);if(error)throw error;message(modal,`${payload.length} ${cfg.label.toLowerCase()} imported successfully.`,false)}document.dispatchEvent(new CustomEvent("content-os:data-changed",{detail:{type:type==="creator"?"creator":type==="video"?"video":type==="product"?"product":"taxonomy"}}));setTimeout(()=>modal.remove(),700)}catch(e){message(modal,e.message||"Import failed.",true);btn.disabled=false}}

async function normalize(type,rows){if(["niches","pillars","topics","keywords","tags"].includes(type))return normalizeTaxonomy(type,rows);const {data:niches}=await supabase.from("niches").select("id,niche_code");const nicheMap=new Map((niches||[]).map(x=>[String(x.niche_code).toUpperCase(),x.id]));if(type==="creator")return rows.filter(r=>r.creator_name?.trim()).map(r=>({...r,niche_id:nicheMap.get(String(r.niche_code||"").toUpperCase())||null}));if(type==="product")return rows.filter(r=>r.product_name?.trim()).map(r=>({...r,niche_id:nicheMap.get(String(r.niche_code||"").toUpperCase())||null,price:num(r.price),commission_rate:num(r.commission_rate),affiliate_potential:num(r.affiliate_potential),repeat_purchase:bool(r.repeat_purchase)}));const [creators,pillars,topics]=await Promise.all([supabase.from("creators").select("id,handle,creator_code"),supabase.from("pillars").select("id,pillar_code"),supabase.from("topics").select("id,topic_code")]);const creatorMap=new Map((creators.data||[]).map(x=>[norm(x.handle||x.creator_code),x.id])),pillarMap=new Map((pillars.data||[]).map(x=>[norm(x.pillar_code),x.id])),topicMap=new Map((topics.data||[]).map(x=>[norm(x.topic_code),x.id]));return rows.filter(r=>r.video_id?.trim()).map(r=>({...r,creator_id:creatorMap.get(norm(r.creator_handle))||null,niche_id:nicheMap.get(String(r.niche_code||"").toUpperCase())||null,pillar_id:pillarMap.get(norm(r.pillar_code))||null,topic_id:topicMap.get(norm(r.topic_code))||null}));}

async function normalizeTaxonomy(type,rows){const [niches,pillars,topics]=await Promise.all([supabase.from("niches").select("id,niche_code"),supabase.from("pillars").select("id,pillar_code"),supabase.from("topics").select("id,topic_code")]);const nm=new Map((niches.data||[]).map(x=>[norm(x.niche_code),x.id])),pm=new Map((pillars.data||[]).map(x=>[norm(x.pillar_code),x.id])),tm=new Map((topics.data||[]).map(x=>[norm(x.topic_code),x.id]));return rows.filter(r=>r.name?.trim()||r.keyword?.trim()).map(r=>{const p={...r};delete p.niche_code;delete p.pillar_code;delete p.topic_code;if(type!=="niches")p.niche_id=nm.get(norm(r.niche_code))||null;if(["topics","keywords","tags"].includes(type))p.pillar_id=pm.get(norm(r.pillar_code))||null;if(["keywords","tags"].includes(type))p.topic_id=tm.get(norm(r.topic_code))||null;if(type==="tags")p.slug=slug(r.name);return p})}

async function normalizeAll(rows){const valid=["niches","pillars","topics","keywords","tags"];const groups=Object.fromEntries(valid.map(t=>[t,[]]));rows.forEach(r=>{const type=norm(r.type);if(!valid.includes(type))return;const base={...r,name:(r.name||"").trim(),code:(r.code||"").trim(),description:(r.description||"").trim()||null,status:(r.status||"active").trim()||"active"};if(type==="keywords"){base.keyword=base.name;base.keyword_code=base.code||`KW-${Date.now()}-${groups[type].length+1}`;base.category=(r.category||"").trim()||null;base.vietnamese_meaning=(r.vietnamese_meaning||"").trim()||null;base.platform=(r.platform||"").trim()||null;delete base.name;delete base.code}else if(type==="niches"){base.niche_code=base.code||null;delete base.code}else if(type==="pillars"){base.pillar_code=base.code||`PIL-${Date.now()}-${groups[type].length+1}`;delete base.code}else if(type==="topics"){base.topic_code=base.code||`TOP-${Date.now()}-${groups[type].length+1}`;delete base.code}delete base.type;groups[type].push(base)});const normalized={};for(const type of valid){normalized[type]=await normalizeTaxonomy(type,groups[type])}return normalized}

function parseCsv(text){const lines=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))lines.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))lines.push(row);const headers=(lines.shift()||[]).map(x=>x.trim());return lines.map(a=>Object.fromEntries(headers.map((h,i)=>[h,(a[i]||"").trim()])))}
function norm(v){return String(v||"").trim().toLowerCase().replace(/^@/,"")}function num(v){return v==null||v===""?null:Number(v)}function bool(v){return ["true","yes","1","y"].includes(String(v).toLowerCase())}function slug(v){return norm(v).replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}function download(text,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",text],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}function message(modal,text,error){const box=modal.querySelector("[data-message]");box.textContent=text;box.classList.toggle("error",error);box.classList.remove("hidden")}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c]))}

init();
