const routes={dashboard:{title:"Overview",breadcrumb:"Workspace",file:"pages/dashboard.html"},library:{title:"Library",breadcrumb:"Library",file:"pages/library.html"},calendar:{title:"Calendar",breadcrumb:"Calendar",file:"pages/calendar.html"},tracking:{title:"Published Videos",breadcrumb:"Tracking",file:"pages/tracking.html"},analytics:{title:"Performance",breadcrumb:"Tracking",file:"pages/analytics.html"},taxonomy:{title:"Taxonomy",breadcrumb:"System",file:"pages/niches.html"},niches:{title:"Taxonomy",breadcrumb:"System",file:"pages/niches.html"},settings:{title:"Settings",breadcrumb:"System",file:"pages/settings.html"}};
const contextMenus={
 dashboard:{label:"OVERVIEW",items:[{label:"Workspace",href:"#dashboard",icon:"⌂"},{label:"Library",href:"#library",icon:"□"}]},
 library:{label:"LIBRARY",items:[{label:"Creators",href:"#library",icon:"◎"},{label:"Videos",href:"#library",icon:"▶"},{label:"Content",href:"#library",icon:"✦"}]},
 calendar:{label:"CALENDAR",items:[{label:"Schedule",href:"#calendar",icon:"□"},{label:"Upcoming",href:"#calendar",icon:"◷"}]},
 tracking:{label:"TRACKING",items:[{label:"Published Videos",href:"#tracking",icon:"↗"},{label:"Performance",href:"#analytics",icon:"◒"}]},
 analytics:{label:"TRACKING",items:[{label:"Published Videos",href:"#tracking",icon:"↗"},{label:"Performance",href:"#analytics",icon:"◒"}]},
 taxonomy:{label:"TAXONOMY",items:[{label:"Niches",href:"#taxonomy",icon:"◈"},{label:"Pillars",href:"#taxonomy",icon:"◉"},{label:"Topics",href:"#taxonomy",icon:"◇"},{label:"Keywords",href:"#taxonomy",icon:"⌕"},{label:"Tags",href:"#taxonomy",icon:"#"}]},
 niches:{label:"TAXONOMY",items:[{label:"Niches",href:"#taxonomy",icon:"◈"},{label:"Pillars",href:"#taxonomy",icon:"◉"},{label:"Topics",href:"#taxonomy",icon:"◇"},{label:"Keywords",href:"#taxonomy",icon:"⌕"},{label:"Tags",href:"#taxonomy",icon:"#"}]},
 settings:{label:"SYSTEM",items:[{label:"Settings",href:"#settings",icon:"⚙"},{label:"Taxonomy",href:"#taxonomy",icon:"◈"}]}
};
function loadPage(pageName){const route=routes[pageName]||routes.dashboard;const pageContent=document.getElementById("pageContent");const pageTitle=document.getElementById("pageTitle");const breadcrumb=document.getElementById("pageBreadcrumb");if(pageTitle)pageTitle.textContent=route.title;if(breadcrumb)breadcrumb.textContent=route.breadcrumb;renderContextNavigation(pageName);fetch(route.file).then(response=>{if(!response.ok)throw new Error("Page not found");return response.text()}).then(html=>{pageContent.innerHTML=html;if(pageName==="dashboard")initDashboardWorkspace();if(pageName==="library")import("./library.js").then(module=>module.initLibrary()).catch(error=>console.error("Library module failed to load:",error));if(pageName==="tracking")initTrackingWorkspace();if(pageName==="analytics")initAnalyticsWorkspace();if(pageName==="taxonomy"||pageName==="niches")import("./taxonomy.js").then(module=>module.initTaxonomy()).catch(error=>console.error("Taxonomy module failed to load:",error));}).catch(error=>{pageContent.innerHTML=`<div class="card"><div class="empty-state"><div class="empty-state-icon">⚠</div><strong>Unable to load page</strong><p>${error.message}</p></div></div>`});updateActiveNavigation(pageName)}
function renderContextNavigation(pageName){const nav=document.getElementById("contextNav");if(!nav)return;const config=contextMenus[pageName]||contextMenus.dashboard;nav.innerHTML=`<div class="nav-section"><span class="nav-label">${config.label}</span>${config.items.map((item,index)=>`<a href="${item.href}" class="nav-item ${index===0?'active':''}"><span class="nav-icon">${item.icon}</span><span>${item.label}</span></a>`).join("")}</div><div class="nav-section"><span class="nav-label">FILTER</span><div class="context-filter-list"><button type="button">Platform <span>⌄</span></button><button type="button">Status <span>⌄</span></button><button type="button">Niche <span>⌄</span></button></div></div>`}
function updateActiveNavigation(pageName){document.querySelectorAll(".global-nav-item").forEach(item=>item.classList.toggle("active",item.getAttribute("href")==="#"+pageName||pageName==="analytics"&&item.getAttribute("href")==="#tracking"));document.querySelectorAll(".nav-item").forEach(item=>item.classList.remove("active"));const first=document.querySelector("#contextNav .nav-item");if(first)first.classList.add("active")}
function initRouter(){const hash=window.location.hash.replace("#","");loadPage(hash||"dashboard");window.addEventListener("hashchange",()=>loadPage(window.location.hash.replace("#","")||"dashboard"))}
