import { supabase } from "./supabase.js";

const TYPES=[
 {key:"niches",label:"Niches",singular:"Niche",table:"niches"},
 {key:"pillars",label:"Pillars",singular:"Pillar",table:"pillars"},
 {key:"topics",label:"Topics",singular:"Topic",table:"topics"},
 {key:"keywords",label:"Keywords",singular:"Keyword",table:"keywords"},
 {key:"tags",label:"Tags",singular:"Tag",table:"tags"}
];
let active="niches",cache=[];
export async function initTaxonomy(){const root=document.getElementById("taxonomyWorkspace");if(!root||root.dataset.initialized==="true")return;root.dataset.initialized="true";bind(root);await load(root)}
function cfg(){return TYPES.find(t=>t.key===active)||TYPES[0]}
function bind(root){root.querySelectorAll("[data-taxonomy-type]").forEach(btn=>btn.addEventListener("click",async()=>{active=btn.dataset.taxonomyType;root.querySelectorAll("[data-taxonomy-type]").forEach(b=>b.classList.toggle("active",b===btn));reset(root);await load(root)}));root.querySelector("#taxonomySearch")?.addEventListener("input",e=>render(root,e.target.value));root.querySelector("#taxonomyForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector("button[type=submit]");button.disabled=true;try{await save(form);reset(root);await load(root);notice(root,`${cfg().singular} saved.`)}catch(err){notice(root,err.message||"Could not save taxonomy item.",true)}finally{button.disabled=false}});root.addEventListener("click",async e=>{const edit=e.target.closest("[data-tax-edit]"),del=e.target.closest("[data-tax-delete]");if(edit){const row=cache.find(x=>String(x.id)===String(edit.dataset.taxEdit));if(row)fill(root,row);return}if(del){if(!confirm(`Delete this ${cfg().singular.toLowerCase()}?`))return;const {error}=await supabase.from(cfg().table).delete().eq("id",del.dataset.taxDelete);if(error)notice(root,error.message,true);else await load(root)}if(e.target.closest("#taxonomyCancel"))reset(root)})}
async function load(root){const c=cfg();root.querySelector("#taxonomyLoading")?.classList.remove("hidden");try{let q=supabase.from(c.table).select("*").limit(300);if(c.table==="niches")q=q.order("sort_order");else q=q.order("created_at",{ascending:false});const {data,error}=await q;if(error)throw error;cache=data||[];root.querySelector("#taxonomyCount").textContent=String(cache.length);updateForm(root);render(root,root.querySelector("#taxonomySearch")?.value||"")}catch(error){cache=[];root.querySelector("#taxonomyCount").textContent="0";root.querySelector("#taxonomyTableBody").innerHTML=`<tr><td colspan="6"><div class="empty-state compact"><strong>Could not load ${c.label}</strong><p>${esc(error.message)}</p></div></td></tr>`}finally{root.querySelector("#taxonomyLoading")?.classList.add("hidden")}}
async function save(form){const v=Object.fromEntries(new FormData(form).entries()),c=cfg(),id=form.dataset.editId||null;let p={};if(c.table==="niches")p={name:v.name?.trim(),niche_code:v.code?.trim()||null,description:v.description?.trim()||null,status:"active"};if(c.table==="pillars")p={pillar_code:v.code?.trim()||`PIL-${Date.now()}`,niche_id:v.niche_id||null,name:v.name?.trim(),description:v.description?.trim()||null,status:"active"};if(c.table==="topics")p={topic_code:v.code?.trim()||`TOP-${Date.now()}`,niche_id:v.niche_id||null,pillar_id:v.pillar_id||null,name:v.name?.trim(),description:v.description?.trim()||null,status:"active"};if(c.table==="keywords")p={keyword_code:v.code?.trim()||`KW-${Date.now()}`,niche_id:v.niche_id||null,pillar_id:v.pillar_id||null,topic_id:v.topic_id||null,keyword:v.name?.trim(),category:v.category?.trim()||null,vietnamese_meaning:v.meaning?.trim()||null,platform:v.platform?.trim()||null,status:"active"};if(c.table==="tags")p={name:v.name?.trim(),slug:slugify(v.name),description:v.description?.trim()||null,niche_id:v.niche_id||null,pillar_id:v.pillar_id||null,topic_id:v.topic_id||null};if(!p.name&&!p.keyword)throw new Error(`${c.singular} name is required.`);if(c.table!=="niches"&&!p.niche_id)throw new Error("Niche is required.");const q=id?supabase.from(c.table).update(p).eq("id",id):supabase.from(c.table).insert(p);const {error}=await q;if(error)throw error}
function updateForm(root){const c=cfg();root.querySelector("#taxonomyFormTitle").textContent=`Add ${c.singular}`;root.querySelector("#taxonomySubmit").textContent=`Add ${c.singular}`;root.querySelector("#taxonomyDescription").textContent=`Manage ${c.label.toLowerCase()} and their taxonomy relationships.`;root.querySelector("#nicheCodeField")?.classList.toggle("hidden",c.table!=="niches");root.querySelector("#nicheParentField")?.classList.toggle("hidden",!["pillars","topics","keywords","tags"].includes(c.table));root.querySelector("#pillarParentField")?.classList.toggle("hidden",!["topics","keywords","tags"].includes(c.table));root.querySelector("#topicParentField")?.classList.toggle("hidden",!["keywords","tags"].includes(c.table));["keywordExtraFields","keywordMeaningField","keywordPlatformField"].forEach(id=>root.querySelector(`#${id}`)?.classList.toggle("hidden",c.table!=="keywords"));loadParents(root)}
async function loadParents(root){const niche=root.querySelector("#taxonomyNiche"),pillar=root.querySelector("#taxonomyPillar"),topic=root.querySelector("#taxonomyTopic");if(niche){const {data}=await supabase.from("niches").select("id,name,niche_code").eq("status","active").order("sort_order");niche.innerHTML='<option value="">Select niche</option>'+(data||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} (${esc(x.niche_code)})</option>`).join("")}if(pillar){const {data}=await supabase.from("pillars").select("id,name,pillar_code").order("name");pillar.innerHTML='<option value="">Select pillar</option>'+(data||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} (${esc(x.pillar_code)})</option>`).join("")}if(topic){const {data}=await supabase.from("topics").select("id,name,topic_code").order("name");topic.innerHTML='<option value="">Select topic</option>'+(data||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} (${esc(x.topic_code)})</option>`).join("")}}
function render(root,search=""){const needle=search.trim().toLowerCase(),filtered=cache.filter(r=>!needle||Object.values(r).some(v=>String(v??"").toLowerCase().includes(needle))),body=root.querySelector("#taxonomyTableBody");if(!filtered.length){body.innerHTML=`<tr><td colspan="6"><div class="empty-state compact"><strong>No ${cfg().label.toLowerCase()} found</strong><p>${needle?"Try another search.":"Add your first item above."}</p></div></td></tr>`;return}body.innerHTML=filtered.map(r=>`<tr><td><strong>${esc(r.name||r.keyword||"Untitled")}</strong></td><td>${esc(r.niche_code||r.keyword_code||r.slug||r.pillar_code||r.topic_code||"—")}</td><td>${esc(r.description||r.vietnamese_meaning||r.category||"—")}</td><td><span class="badge">${esc(r.status||"active")}</span></td><td>${esc(date(r.created_at))}</td><td class="row-actions"><button class="table-action" data-tax-edit="${esc(r.id)}">Edit</button><button class="table-action danger" data-tax-delete="${esc(r.id)}">Delete</button></td></tr>`).join("")}
function fill(root,row){const form=root.querySelector("#taxonomyForm");form.dataset.editId=row.id;form.querySelector('[name="name"]').value=row.name||row.keyword||"";form.querySelector('[name="code"]').value=row.niche_code||row.pillar_code||row.topic_code||row.keyword_code||"";["description","category","meaning","platform"].forEach(n=>{const f=form.querySelector(`[name="${n}"]`);if(f)f.value=row[n==="meaning"?"vietnamese_meaning":n]||""});["niche_id","pillar_id","topic_id"].forEach(n=>{const f=form.querySelector(`[name="${n}"]`);if(f)f.value=row[n]||""});root.querySelector("#taxonomyFormTitle").textContent=`Edit ${cfg().singular}`;root.querySelector("#taxonomySubmit").textContent=`Save ${cfg().singular}`;root.querySelector("#taxonomyCancel").classList.remove("hidden");form.scrollIntoView({behavior:"smooth",block:"center"})}
function reset(root){const form=root.querySelector("#taxonomyForm");form?.reset();if(form)delete form.dataset.editId;root.querySelector("#taxonomyCancel")?.classList.add("hidden");updateForm(root)}
function notice(root,text,error=false){const box=root.querySelector("#taxonomyNotice");box.textContent=text;box.classList.toggle("error",error);box.classList.remove("hidden");setTimeout(()=>box.classList.add("hidden"),3000)}
function slugify(v){return String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c]))}
