import { supabase } from "./supabase.js";

export async function initTrackingWorkspace(){
 const root=document.getElementById("trackingWorkspace");if(!root||root.dataset.initialized==="true")return;root.dataset.initialized="true";
 let rows=[],filter="all";
 async function load(){const {data,error}=await supabase.from("videos").select("id,video_id,title,status,published_at,views,likes,comments,shares,saves,followers_gained,platform,creators(creator_name,handle),niches(name),pillars(name),topics(name)").eq("status","published").order("published_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(error)throw error;rows=data||[]}
 function render(){const filtered=filter==="all"?rows:rows.filter(r=>filter==="low"?Number(r.views||0)<1000:Number(r.views||0)>=1000);const total=(k)=>rows.reduce((s,r)=>s+Number(r[k]||0),0),avgViews=rows.length?Math.round(total("views")/rows.length):0;root.innerHTML=`<div class="stat-grid tracking-stats"><div class="stat-card"><div class="stat-label">PUBLISHED</div><div class="stat-value">${rows.length}</div><div class="stat-meta">Videos being tracked</div></div><div class="stat-card"><div class="stat-label">TOTAL VIEWS</div><div class="stat-value">${fmt(total("views"))}</div><div class="stat-meta">Across published videos</div></div><div class="stat-card"><div class="stat-label">LIKES</div><div class="stat-value">${fmt(total("likes"))}</div><div class="stat-meta">Total engagement</div></div><div class="stat-card"><div class="stat-label">SAVES</div><div class="stat-value">${fmt(total("saves"))}</div><div class="stat-meta">Content saves</div></div><div class="stat-card"><div class="stat-label">AVG VIEWS</div><div class="stat-value">${fmt(avgViews)}</div><div class="stat-meta">Per published video</div></div></div><div class="card"><div class="card-header"><div><h3>Performance Tracking</h3><span class="card-header-note">Update metrics directly after a video is published.</span></div><select class="workspace-select" id="trackingFilter"><option value="all">All videos</option><option value="low" ${filter==="low"?"selected":""}>Under 1K views</option><option value="high" ${filter==="high"?"selected":""}>1K+ views</option></select></div><div class="table-wrapper"><table class="data-table tracking-table"><thead><tr><th>Video</th><th>Published</th><th>Views</th><th>Likes</th><th>Comments</th><th>Shares</th><th>Saves</th><th>Followers</th><th>Actions</th></tr></thead><tbody>${filtered.map(row=>`<tr><td><div class="source-title">${esc(row.video_id||row.title||"Untitled")}</div><div class="source-subtitle">${esc(row.creators?.creator_name||row.creators?.handle||"—")} · ${esc(row.pillars?.name||"")}</div></td><td>${date(row.published_at)}</td><td>${editable(row,"views")}</td><td>${editable(row,"likes")}</td><td>${editable(row,"comments")}</td><td>${editable(row,"shares")}</td><td>${editable(row,"saves")}</td><td>${editable(row,"followers_gained")}</td><td><button class="table-action" data-track-edit="${row.id}">Edit metrics</button></td></tr>`).join("")||`<tr><td colspan="9"><div class="empty-state compact"><strong>No published videos found</strong><p>Set a video status to Published from Library first.</p></div></td></tr>`}</tbody></table></div></div>`;root.querySelector("#trackingFilter").onchange=e=>{filter=e.target.value;render()};root.querySelectorAll("[data-track-edit]").forEach(b=>b.onclick=()=>editMetrics(b.dataset.trackEdit));root.querySelectorAll("[data-track-field]").forEach(el=>el.ondblclick=()=>inlineMetric(el))}
 function editable(r,key){return `<span class="tracking-editable" data-track-field="${key}" data-track-id="${r.id}">${fmt(r[key])}</span>`}
 async function editMetrics(id){const r=rows.find(x=>x.id===id);if(!r)return;const modal=document.createElement("div");modal.className="library-edit-overlay";modal.innerHTML=`<div class="library-edit-modal"><div class="modal-header"><div><h3>Update Performance</h3><p>${esc(r.video_id||r.title||"Video")}</p></div><button class="modal-close" data-close>×</button></div><form><div class="edit-grid">${["views","likes","comments","shares","saves","followers_gained"].map(k=>`<label>${label(k)}<input name="${k}" type="number" min="0" value="${Number(r[k]||0)}"></label>`).join("")}</div><div class="modal-actions"><button type="button" class="button secondary" data-close>Cancel</button><button class="button primary">Save</button></div></form></div>`;document.body.appendChild(modal);modal.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>modal.remove());modal.querySelector("form").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),payload={};["views","likes","comments","shares","saves","followers_gained"].forEach(k=>payload[k]=Number(fd.get(k)||0));const {error}=await supabase.from("videos").update(payload).eq("id",id);if(error){alert(error.message);return}Object.assign(r,payload);modal.remove();render();document.dispatchEvent(new CustomEvent("content-os:data-changed",{detail:{type:"video"}}))}}
 function inlineMetric(el){const id=el.dataset.trackId,key=el.dataset.trackField,r=rows.find(x=>x.id===id);if(!r)return;const input=document.createElement("input");input.type="number";input.min="0";input.value=Number(r[key]||0);input.className="inline-edit-input";el.replaceChildren(input);input.focus();input.select();let done=false;const save=async()=>{if(done)return;done=true;const value=Number(input.value||0),{error}=await supabase.from("videos").update({[key]:value}).eq("id",id);if(error){alert(error.message);render();return}r[key]=value;render()};input.onblur=save;input.onkeydown=e=>{if(e.key==="Enter")save();if(e.key==="Escape"){done=true;render()}}}
 function label(k){return k.replace("followers_gained","Followers gained").replace(/\b\w/g,c=>c.toUpperCase())}function fmt(v){return new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(Number(v||0))}function date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c]))}
 root.innerHTML='<div class="card"><div class="empty-state"><strong>Loading tracking...</strong></div></div>';try{await load();render()}catch(e){root.innerHTML=`<div class="card"><div class="empty-state"><strong>Tracking could not load</strong><p>${esc(e.message)}</p></div></div>`}
}
window.initTrackingWorkspace=initTrackingWorkspace;
